/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OrdinalsIndexerConfig {
  bitcoinRpcUrl?: string
  bitcoinRpcUsername?: string
  bitcoinRpcPassword?: string
  workingDir?: string
  logsEnabled?: boolean
}
export class OrdinalsIndexer {
  constructor(configOverrides?: OrdinalsIndexerConfig | undefined | null)
  onBlock(callback: (block: any) => boolean): void
  onBlockRollBack(callback: (block: any) => boolean): void
  streamBlocks(): void
  replayBlocks(blocks: Array<number>): void
  replayBlockRange(startBlock: number, endBlock: number): void
  terminate(): void
}
